# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "nedlia-terraform-state"
    dynamodb_table = "nedlia-terraform-locks"
    encrypt        = true
    key            = "static-website/terraform.tfstate"
    region         = "us-east-1"
  }
}
